### ISSUE TITLE
can't not run with python3

### ISSUE THREAD

**Issue by Green-li** [kingfengji/gcForest#40]
Environment : python3.6, Centos 7.

code in `lib/gcforest/layers/fg_pool_layer.py`:
```
class FGPoolLayer(BaseLayer):
    def __init__(self, layer_config, data_cache):
        """
        Pooling Layer (MaxPooling, AveragePooling)
        """
        super(FGPoolLayer, self).__init__(layer_config, data_cache)
        self.win_x = self.get_value("win_x", None, int, required=True)
        self.win_y = self.get_value("win_y", None, int, required=True)
        self.pool_method = self.get_value("pool_method", "avg", basestring)
.....
```
while run using the config `examples/demo_mnist-gc.json`,  it has an error:
```
Traceback (most recent call last):
  File "examples/demo_mnist.py", line 55, in <module>
    gc = GCForest(config)
  File "lib/gcforest/gcforest.py", line 16, in __init__
    self.fg = FGNet(self.config["net"], self.train_config.data_cache)
  File "lib/gcforest/fgnet.py", line 36, in __init__
    layer = get_layer(layer_config, self.data_cache)
  File "lib/gcforest/layers/__init__.py", line 32, in get_layer
    layer = layer_class(layer_config, data_cache)
  File "lib/gcforest/layers/fg_pool_layer.py", line 27, in __init__
    self.pool_method = self.get_value("pool_method", "avg", basestring)
NameError: name 'basestring' is not defined
```
the basestring function is no longer used in python3.

**Comment by kingfengji** [comment]
change basestring to six.string_types (and remember to import six) if you are using py3.5

**Comment by madarax64** [comment]
Hello @Green-li ,
I'm not sure if you've found a solution yet. I was able to make a few modifications which resolved the issue in win_utils.py - I hope @kingfengji can confirm they don't mess anything up too much?

Specifically in the win_utils.py file, I made four modifications based on the observed error messages. Just below line 18, you may consider adding the following two lines:

`k = int(k)
 di = int(di)`

Specifically, we're typecasting the `k` and `di` variables to `int`s. 

Next, inside the `get_windows()` method, locate the following two lines:
`nh = (h - win_y) / stride_y + 1
    nw = (w - win_x) / stride_x + 1`

And add the following two lines below them:

`nh = int(nh)
nw = int(nw)`

Which are just more typecasts. This seemed to fix the issue for me, and I was able to use gcForest in both Cascade and Multigrained Scanning mode.

Big ups to @kingfengji . I hope my modifications aren't too troublesome though.

Please update this thread with the results of these modifications on your code. It'd be nice to know if they work for you too.

Regards,
M.

**Comment by marooncn** [comment]
Added @madarax64 , also modify fg_pool_layer.py,  add
` nh = int(nh)`
  `nw = int(nw)`
below
`nh = (h - 1) / win_y + 1`
 `nw = (w - 1) / win_x + 1`

**Comment by Tessic** [comment]
it worked  @marooncn  @madarax64. but another error occurs:
```
Traceback (most recent call last): 
  File "/examples/demo_mnist.py", line 77, in <module>
    y_pred = gc.predict(X_test)
  File "\lib\gcforest\gcforest.py", line 61, in predict
    y_proba = self.predict_proba(X)
  File "\lib\gcforest\gcforest.py", line 56, in predict_proba
    X = self.fg.transform(X)
  File "\lib\gcforest\fgnet.py", line 68, in transform
    layer.transform()
  File "\lib\gcforest\layers\fg_win_layer.py", line 130, in transform
    y_proba = est.predict_proba(X_win)
AttributeError: 'NoneType' object has no attribute 'predict_proba'
```

**Comment by Fanersama** [comment]
> it worked @marooncn @madarax64. but another error occurs:
> 
> ```
> Traceback (most recent call last): 
>   File "/examples/demo_mnist.py", line 77, in <module>
>     y_pred = gc.predict(X_test)
>   File "\lib\gcforest\gcforest.py", line 61, in predict
>     y_proba = self.predict_proba(X)
>   File "\lib\gcforest\gcforest.py", line 56, in predict_proba
>     X = self.fg.transform(X)
>   File "\lib\gcforest\fgnet.py", line 68, in transform
>     layer.transform()
>   File "\lib\gcforest\layers\fg_win_layer.py", line 130, in transform
>     y_proba = est.predict_proba(X_win)
> AttributeError: 'NoneType' object has no attribute 'predict_proba'
> ```
> 
> it seems like that can't find the `self.estimator1d[ti]` because I set the keep_model_in_mem false. how can i solve this?      @Tessic @kingfengji
我也遇到了同样的问题，请问您解决了吗？
I meet the same question, how did you deal with this ? very thanks
